version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Show current branch
          command: echo ${CURRENT_BRANCH}
      - restore_cache:
          keys: 
            - app-{{ checksum "package.json" }}
            - app-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
           -node_modules
          keys: app-{{ checksum "package.json" }}
  
  deploy-to-aws-cloudfront:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Show current branch
          command: echo ${CURRENT_BRANCH}
      - run:
          name: Installing AWS CLI
          working_directory: /
          command: | 
            sudo apt-get -y -qq update
            sudo app-get install -y awscli
            sudo app-get install -y python-pip python-dev build-essential
      - run:
          name: Build Project
          command: |
            npm install
            npm run build
            cd build 
            zip ../build.zip -r * .[^.]*
            echo "Build successful"
      - run:
          name: Deploy to AWS Cloudfront
          command: |
            if ["${CURRENT_BRANCH}" === "master"]
            then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_PRODUCTION} --delete
            elif ["${CURRENT_BRANCH}" === "staging"]
            then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_STAGING} --delete
            else
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_DEV_BUCKET} --delete
            fi

              deploy-to-aws-s3:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Show current branch
          command: echo ${CURRENT_BRANCH}
      - run:
          name: Installing AWS CLI
          working_directory: /
          command: | 
            sudo apt-get -y -qq update
            sudo app-get install -y awscli
            sudo app-get install -y python-pip python-dev build-essential
      - run:
          name: Build Project
          command: |
            npm install
            npm run build
            cd build 
            zip ../build.zip -r * .[^.]*
            echo "Build successful"
      - run:
          name: Deploy to AWS S3
          command: |
            aws configure set preview.cloudfront
            if ["${CURRENT_BRANCH}" === "master"]
            then
              aws cloudfront create-invalidation --distribution-id ${PRODUCTION_DESTRIBUTION} --path /\*
            elif ["${CURRENT_BRANCH}" === "staging"]
            then
              aws cloudfront create-invalidation --distribution-id ${STAGING_DESTRIBUTION} --path /\*
            else
              aws cloudfront create-invalidation --distribution-id ${DEV_DESTRIBUTION} --path /\*
            fi

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy-to-aws-s3:
        requires:
          - build
        filters:
          branches: 
            only:
              - develop
              - staging
              - master
      - deploy-to-aws-cloudfront:
        requires:
          - deploy-to-aws-s3
        filters:
          branches: 
            only:
              - develop
              - staging
              - master
              









